
CREATE TABLE IF NOT EXISTS games(
 id INT AUTO_INCREMENT PRIMARY KEY,
 gameCode VARCHAR(60) UNIQUE NOT NULL,
 gameName VARCHAR(50) UNIQUE NOT NULL,
 gameIcon VARCHAR(100) NOT NULL,
 description VARCHAR(255) NOT NULL,
 holiday BOOLEAN NOT NULL DEFAULT 0,
 isActive BOOLEAN NOT NULL DEFAULT 1,
 isMaster BOOLEAN NOT NULL DEFAULT 1,
 masterId INT,FOREIGN KEY (masterId) REFERENCES games(id),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ALTER TABLE games ADD COLUMN isMaster BOOLEAN NOT NULL DEFAULT 0;
-- ALTER TABLE games ADD FOREIGN KEY (masterId) REFERENCES games(id);
