

CREATE TABLE IF NOT EXISTS game_states(
 stateId INT AUTO_INCREMENT PRIMARY KEY,
 gameId INT NOT NULL,
 gameDate DATE NOT NULL,
 gameState VARCHAR(50) NOT NULL,
 showInLive TINYINT NOT NULL DEFAULT 0,
 showInPending TINYINT NOT NULL DEFAULT 0,
 showInDeclared TINYINT NOT NULL DEFAULT 0,
 showInUpcoming TINYINT NOT NULL DEFAULT 0,
 createdAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (gameId) REFERENCES games(id)
 ON DELETE CASCADE
 ON UPDATE CASCADE
);

CREATE INDEX idx_states_game_date 
ON game_states(gameId, gameDate);
