CREATE TABLE IF NOT EXISTS game_calendar (

  calendarId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  gameId INT NOT NULL,
  gameDate DATE NOT NULL,
  isHoliday TINYINT(1) NOT NULL DEFAULT 0,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT uq_game_calendar UNIQUE (gameId, gameDate),

 FOREIGN KEY (gameId) REFERENCES games(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
