


CREATE TABLE IF NOT EXISTS game_results (
  pkResultId INT AUTO_INCREMENT PRIMARY KEY,
  gameId INT NOT NULL,
  gameDate DATE NOT NULL,
  result VARCHAR(255) NOT NULL,
  previousResult VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (gameId) REFERENCES games(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
 
CONSTRAINT uq_game_date UNIQUE (gameId, gameDate),

);